version: '3.6'

services:
  # auth:
  #   build:
  #     context: .
  #     dockerfile: ./auth/Dockerfile
  #   ports:
  #     - "9001:9001"
  #   env_file:
  #     - ./.env
  #   networks:
  #     - go-oauth2-server_network

  # resource:
  #   build:
  #     context: .
  #     dockerfile: ./resource/Dockerfile
  #   ports:
  #     - "9002:9002"
  #   env_file:
  #     - ./.env
  #   networks:
  #     - go-oauth2-server_network

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_service
    # depends_on:
    #   - auth
    #   - resource
    networks:
      - go-oauth2-server_network

volumes:
  data:

networks:
  go-oauth2-server_network:
    driver: "bridge"
